import { api } from "@utils/axios";
import { supabase } from "../config/supabaseClient";
import type { FormData as ProposalFormState } from "../types/proponent-form";
import { PriorityArea } from "../types/proposal";

type ProposalResponse = {
  message: string;
};
// --- FETCH FUNCTIONS ---

export const fetchAgencies = async () => {
  const { data, error } = await supabase.from("agencies").select("*").order("name");
  if (error) {
    console.error("Error loading agencies:", error);
    return [];
  }
  return data || [];
};

export const fetchTags = async () => {
  const { data, error } = await supabase.from("tags").select("*").order("name");
  if (error) {
    console.error("Error loading tags:", error);
    return [];
  }
  return data || [];
};

export const fetchStations = async () => {
  const { data, error } = await supabase.from("research_stations").select("*").order("name");
  if (error) {
    console.error("Error loading stations:", error);
    return [];
  }
  return data || [];
};

export const fetchSectors = async () => {
  const { data, error } = await supabase.from("sectors").select("*").order("name");
  if (error) {
    console.error("Error loading sectors:", error);
    return [];
  }
  return data || [];
};

export const fetchDisciplines = async () => {
  const { data, error } = await supabase.from("disciplines").select("*").order("name");
  if (error) {
    console.error("Error loading disciplines:", error);
    return [];
  }
  return data || [];
};

export const fetchPriorities = async () => {
  const { data, error } = await supabase.from("priorities").select("*").order("name");
  if (error) {
    console.error("Error loading priorities:", error);
    return [];
  }
  return data || [];
};

// --- SUBMIT FUNCTION ---

export const submitProposal = async (formData: ProposalFormState, file: File, proponentId: string) => {
  // 1. Get User Token
  const {
    data: { session },
  } = await supabase.auth.getSession();
  const token = session?.access_token;
  if (!token) throw new Error("User is not logged in. Cannot submit proposal.");

  // 2. Process Agencies (Handle Custom Inputs)
  // We check for temporary IDs (generated by Date.now() in frontend)
  // and create them in the DB before submitting.
  const finalAgencyIds: number[] = [];

  if (formData.cooperatingAgencies && formData.cooperatingAgencies.length > 0) {
    for (const agency of formData.cooperatingAgencies) {
      // Check if ID is temporary (Date.now() produces huge numbers > 1 trillion)
      if (agency.id > 1000000000000) {
        // Insert new agency into Supabase
        const { data: newAgency, error } = await supabase
          .from("agencies")
          .insert({ name: agency.name })
          .select()
          .single();

        if (error) {
          console.error("Failed to create agency:", agency.name, error);
        } else if (newAgency) {
          // Use the REAL ID from database
          finalAgencyIds.push(newAgency.id);
        }
      } else {
        // It's an existing agency, use the ID directly
        finalAgencyIds.push(agency.id);
      }
    }
  }

  // 3. Prepare FormData for Backend
  const submissionData = new FormData();

  // Basic Fields
  submissionData.append("projectTitle", formData.projectTitle);
  submissionData.append("programTitle", formData.programTitle || "");
  submissionData.append("proponentId", proponentId);
  submissionData.append("email", formData.email || "");
  submissionData.append("telephone", formData.telephone || "");
  submissionData.append("plannedStartDate", formData.plannedStartDate || "");
  submissionData.append("plannedEndDate", formData.plannedEndDate || "");
  if (formData.schoolYear) submissionData.append("school_year", formData.schoolYear);

  // Agency & Contact
  submissionData.append("agencyName", formData.agencyName);
  submissionData.append("agencyAddress", formData.agencyAddress);

  // Classification & Enums
  submissionData.append("classificationType", formData.classificationType);

  if (formData.classificationType === "research") {
    submissionData.append("researchType", JSON.stringify(formData.researchType));
  } else {
    submissionData.append("developmentType", formData.developmentType);
  }

  if (formData.implementationMode.singleAgency) submissionData.append("implementationMode", "single_agency");
  else if (formData.implementationMode.multiAgency) submissionData.append("implementationMode", "multi_agency");

  // JSON Arrays
  submissionData.append("budgetItems", JSON.stringify(formData.budgetItems));
  submissionData.append("implementationSite", JSON.stringify(formData.implementationSite));

  // Use our PROCESSED IDs for agencies
  submissionData.append("cooperatingAgencies", JSON.stringify(finalAgencyIds));

  // Strings
  submissionData.append("discipline", formData.discipline);
  submissionData.append("sectorCommodity", formData.sectorCommodity);
  submissionData.append("researchStation", formData.researchStation);

  // ---------------------------------------------------------
  // PRIORITY AREAS LOGIC (Using Enum)
  // ---------------------------------------------------------
  const activePriorities: string[] = [];
  const pAreas = formData.priorityAreas || {};

  // Map the standard boolean flags to the Enum values
  if (pAreas["stand"]) activePriorities.push(PriorityArea.STAND);
  if (pAreas["coconutIndustry"]) activePriorities.push(PriorityArea.COCONUT_INDUSTRY);
  if (pAreas["exportWinners"]) activePriorities.push(PriorityArea.EXPORT_WINNERS);
  if (pAreas["otherPriorityAreas"]) activePriorities.push(PriorityArea.OTHER_PRIORITY_AREAS);
  if (pAreas["supportIndustries"]) activePriorities.push(PriorityArea.SUPPORT_INDUSTRIES);

  // Handle Custom Priorities (Dynamic Keys)
  const standardKeys = ["stand", "coconutIndustry", "exportWinners", "otherPriorityAreas", "supportIndustries"];

  Object.keys(pAreas).forEach((key) => {
    const value = (pAreas as Record<string, boolean>)[key];

    if (value === true && !standardKeys.includes(key)) {
      activePriorities.push(key);
    }
  });

  submissionData.append("priorityAreas", JSON.stringify(activePriorities));

  // File
  submissionData.append("files", file);

  // 4. Send Request
  const res = await api.post<ProposalResponse>("/proposal/create", submissionData, {
    headers: {
      "Content-Type": "multipart/form-data",
    },
    withCredentials: true,
  });

  if (!res) {
    throw new Error(res || "Submission failed");
  }
};
