


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."assessment" AS ENUM (
    'objective_assessment',
    'methodology_assessment',
    'budget_assessment',
    'timeline_assessment'
);


ALTER TYPE "public"."assessment" OWNER TO "postgres";


CREATE TYPE "public"."budget" AS ENUM (
    'ps',
    'mooe',
    'co'
);


ALTER TYPE "public"."budget" OWNER TO "postgres";


CREATE TYPE "public"."development_class" AS ENUM (
    'pilot_testing',
    'tech_promotion'
);


ALTER TYPE "public"."development_class" OWNER TO "postgres";


CREATE TYPE "public"."evaluator_status" AS ENUM (
    'pending',
    'for_review',
    'approve',
    'revise',
    'reject',
    'decline'
);


ALTER TYPE "public"."evaluator_status" OWNER TO "postgres";


CREATE TYPE "public"."evaluator_trackcer_status" AS ENUM (
    'accept',
    'decline',
    'extend',
    'pending'
);


ALTER TYPE "public"."evaluator_trackcer_status" OWNER TO "postgres";


CREATE TYPE "public"."implementation_mode" AS ENUM (
    'single_agency',
    'multi_agency'
);


ALTER TYPE "public"."implementation_mode" OWNER TO "postgres";


CREATE TYPE "public"."priority_area" AS ENUM (
    'stand',
    'export_winners',
    'support_industries',
    'coconut_industry',
    'other_priority_areas'
);


ALTER TYPE "public"."priority_area" OWNER TO "postgres";


CREATE TYPE "public"."projects_status" AS ENUM (
    'on_going',
    'completed',
    'on_hold',
    'blocked'
);


ALTER TYPE "public"."projects_status" OWNER TO "postgres";


CREATE TYPE "public"."proposal_status" AS ENUM (
    'review_rnd',
    'revision_rnd',
    'rejected_rnd',
    'under_evaluation',
    'endorsed_for_funding',
    'funded'
);


ALTER TYPE "public"."proposal_status" OWNER TO "postgres";


CREATE TYPE "public"."quarterly_report" AS ENUM (
    'q1_report',
    'q2_report',
    'q3_report',
    'q4_report'
);


ALTER TYPE "public"."quarterly_report" OWNER TO "postgres";


CREATE TYPE "public"."quarterly_report_status" AS ENUM (
    'submitted',
    'verified',
    'overdue'
);


ALTER TYPE "public"."quarterly_report_status" OWNER TO "postgres";


CREATE TYPE "public"."research_class" AS ENUM (
    'basic',
    'applied'
);


ALTER TYPE "public"."research_class" OWNER TO "postgres";


CREATE TYPE "public"."role" AS ENUM (
    'proponent',
    'rnd',
    'evaluator',
    'rdec',
    'lead_proponent',
    'admin'
);


ALTER TYPE "public"."role" OWNER TO "postgres";


CREATE TYPE "public"."sex" AS ENUM (
    'male',
    'female',
    'prefer_not_to_say'
);


ALTER TYPE "public"."sex" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$BEGIN
  INSERT INTO public.users (id, first_name, middle_ini, last_name,  email, roles)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data ->> 'first_name', ''),
    COALESCE(new.raw_user_meta_data ->> 'middle_ini', ''),
    COALESCE(new.raw_user_meta_data ->> 'last_name', ''),
    new.email,
    CASE
      WHEN jsonb_typeof(new.raw_user_meta_data -> 'roles') = 'array' THEN
        COALESCE(
          NULLIF(
            ARRAY(
              SELECT trim(value)::public.role
              FROM jsonb_array_elements_text(new.raw_user_meta_data -> 'roles') AS t(value)
            ),
            ARRAY[]::public.role[]
          ),
          ARRAY['proponent']::public.role[]
        )
      ELSE
        ARRAY['proponent']::public.role[]
    END
  );

  RETURN new;
END;$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."agencies" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone,
    "city" "text",
    "barangay" "text",
    "street" "text"
);


ALTER TABLE "public"."agencies" OWNER TO "postgres";


ALTER TABLE "public"."agencies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."agencies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."cooperating_agencies" (
    "id" bigint NOT NULL,
    "agency_id" bigint NOT NULL,
    "proposal_id" bigint,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."cooperating_agencies" OWNER TO "postgres";


ALTER TABLE "public"."cooperating_agencies" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."cooperating_aagencies_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."criterion" (
    "id" bigint NOT NULL,
    "rubric_id" integer,
    "name" character varying,
    "description" "text",
    "score" real,
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."criterion" OWNER TO "postgres";


ALTER TABLE "public"."criterion" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."criterion_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."departments" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."departments" OWNER TO "postgres";


ALTER TABLE "public"."departments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."departments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."disciplines" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."disciplines" OWNER TO "postgres";


ALTER TABLE "public"."disciplines" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."disciplines_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."estimated_budget" (
    "id" bigint NOT NULL,
    "proposal_id" bigint,
    "source" character varying,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT "now"(),
    "budget" "public"."budget",
    "item" "text",
    "amount" real
);


ALTER TABLE "public"."estimated_budget" OWNER TO "postgres";


ALTER TABLE "public"."estimated_budget" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."estimated_budget_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."evaluation_scores" (
    "id" bigint NOT NULL,
    "score" smallint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "evaluator_id" "uuid" NOT NULL,
    "assessment" "public"."assessment",
    "proposal_id" bigint
);


ALTER TABLE "public"."evaluation_scores" OWNER TO "postgres";


ALTER TABLE "public"."evaluation_scores" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."evaluation_scores_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."evaluators_specialties" (
    "id" bigint NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "evaluator_id" "uuid",
    "department_id" bigint
);


ALTER TABLE "public"."evaluators_specialties" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."funded_projects" (
    "id" bigint NOT NULL,
    "proposal_id" integer,
    "status" "public"."projects_status",
    "funded_date" "date",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "project_lead_id" "uuid"
);


ALTER TABLE "public"."funded_projects" OWNER TO "postgres";


ALTER TABLE "public"."funded_projects" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."funded_projects_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."implementation_site" (
    "id" bigint NOT NULL,
    "proposal_id" bigint NOT NULL,
    "site_name" "text",
    "city" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."implementation_site" OWNER TO "postgres";


ALTER TABLE "public"."implementation_site" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."implementation_site_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."notifications" (
    "id" bigint NOT NULL,
    "message" "text",
    "is_read" boolean,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone DEFAULT "now"(),
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."notifications" OWNER TO "postgres";


ALTER TABLE "public"."notifications" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."notifications_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."priorities" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."priorities" OWNER TO "postgres";


ALTER TABLE "public"."priorities" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."priorities_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."project_expenses" (
    "id" bigint NOT NULL,
    "project_reports_id" bigint NOT NULL,
    "expenses" bigint,
    "desription" "text",
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."project_expenses" OWNER TO "postgres";


ALTER TABLE "public"."project_expenses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."project expenses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."project_comments" (
    "id" bigint NOT NULL,
    "project_reports_id" bigint NOT NULL,
    "users_id" "uuid",
    "comments" "text"
);


ALTER TABLE "public"."project_comments" OWNER TO "postgres";


ALTER TABLE "public"."project_comments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."project_comments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."project_reports" (
    "id" bigint NOT NULL,
    "funded_project_id" bigint NOT NULL,
    "report_file_url" "text"[],
    "comment" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone,
    "progress" bigint,
    "quarterly_report" "public"."quarterly_report",
    "submitted_by_proponent_id" "uuid",
    "status" "public"."quarterly_report_status"
);


ALTER TABLE "public"."project_reports" OWNER TO "postgres";


ALTER TABLE "public"."project_reports" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."project_reports_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."proposal_assignment_tracker" (
    "id" bigint NOT NULL,
    "proposal_id" bigint NOT NULL,
    "evaluator_id" "uuid",
    "status" "public"."evaluator_trackcer_status",
    "remark" "text",
    "deadline_at" "date",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."proposal_assignment_tracker" OWNER TO "postgres";


ALTER TABLE "public"."proposal_assignment_tracker" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proposal_assignment_tracker_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."proposal_evaluations" (
    "id" bigint NOT NULL,
    "proposal_id" bigint NOT NULL,
    "proposal_evaluators_id" bigint,
    "rubric_id" bigint,
    "comment" character varying,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."proposal_evaluations" OWNER TO "postgres";


ALTER TABLE "public"."proposal_evaluations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proposal_evaluations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."proposal_evaluators" (
    "id" bigint NOT NULL,
    "proposal_id" bigint NOT NULL,
    "status" "public"."evaluator_status",
    "deadline_at" timestamp without time zone NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone,
    "comments_for_evaluators" "text",
    "forwarded_by_rnd" "uuid" NOT NULL,
    "evaluator_id" "uuid" NOT NULL
);


ALTER TABLE "public"."proposal_evaluators" OWNER TO "postgres";


ALTER TABLE "public"."proposal_evaluators" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proposal_evaluators_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."proposal_logs" (
    "id" bigint NOT NULL,
    "proposal_id" integer,
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT "now"(),
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."proposal_logs" OWNER TO "postgres";


ALTER TABLE "public"."proposal_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proposal_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."proposal_reject_summary" (
    "id" bigint NOT NULL,
    "proposal_id" bigint NOT NULL,
    "rnd_id" "uuid",
    "comment" "text",
    "created_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."proposal_reject_summary" OWNER TO "postgres";


ALTER TABLE "public"."proposal_reject_summary" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proposal_reject_summary_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."proposal_revision_summary" (
    "id" bigint NOT NULL,
    "proposal_id" bigint NOT NULL,
    "objective_comment" "text",
    "methodology_comment" "text",
    "budget_comment" "text",
    "timeline_comment" "text",
    "overall_comment" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone,
    "deadline" bigint,
    "rnd_id" "uuid"
);


ALTER TABLE "public"."proposal_revision_summary" OWNER TO "postgres";


ALTER TABLE "public"."proposal_revision_summary" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proposal_revision_summary_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."proposal_rnd" (
    "id" bigint NOT NULL,
    "proposal_id" bigint NOT NULL,
    "rnd_id" "uuid",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."proposal_rnd" OWNER TO "postgres";


ALTER TABLE "public"."proposal_rnd" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proposal_rnd_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."proposal_tags" (
    "id" bigint NOT NULL,
    "proposal_id" bigint NOT NULL,
    "tag_id" bigint,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."proposal_tags" OWNER TO "postgres";


ALTER TABLE "public"."proposal_tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proposal_tags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."proposal_version" (
    "id" bigint NOT NULL,
    "proposal_id" bigint NOT NULL,
    "file_url" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."proposal_version" OWNER TO "postgres";


ALTER TABLE "public"."proposal_version" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proposal_version_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."proposals" (
    "id" bigint NOT NULL,
    "department_id" bigint,
    "project_title" character varying,
    "status" "public"."proposal_status",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone,
    "sector_id" bigint,
    "discipline_id" bigint,
    "agency_id" bigint,
    "program_title" character varying,
    "email" character varying,
    "phone" character varying,
    "research_class" "public"."research_class",
    "development_class" "public"."development_class",
    "implementation_mode" "public"."implementation_mode",
    "plan_start_date" "date",
    "plan_end_date" "date",
    "priority_areas" "public"."priority_area"[],
    "evaluation_deadline_at" timestamp without time zone,
    "proponent_id" "uuid",
    "school_year" "text" DEFAULT ''::"text",
    "duration" bigint
);


ALTER TABLE "public"."proposals" OWNER TO "postgres";


ALTER TABLE "public"."proposals" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."proposals_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rubrics" (
    "id" bigint NOT NULL,
    "name" character varying,
    "description" "text",
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone DEFAULT "now"()
);


ALTER TABLE "public"."rubrics" OWNER TO "postgres";


ALTER TABLE "public"."rubrics" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."rubrics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sectors" (
    "id" bigint NOT NULL,
    "name" character varying NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."sectors" OWNER TO "postgres";


ALTER TABLE "public"."sectors" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sectors_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "created_at" timestamp without time zone DEFAULT "now"(),
    "updated_at" timestamp without time zone
);


ALTER TABLE "public"."tags" OWNER TO "postgres";


ALTER TABLE "public"."tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."evaluators_specialties" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."user_specialties_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."users" (
    "id" "uuid" NOT NULL,
    "first_name" character varying,
    "email" character varying,
    "roles" "public"."role"[] DEFAULT ARRAY['proponent'::"public"."role"],
    "created_at" timestamp without time zone DEFAULT "now"(),
    "last_name" character varying,
    "middle_ini" "text",
    CONSTRAINT "users_middle_ini_check" CHECK (("length"("middle_ini") = 1))
);


ALTER TABLE "public"."users" OWNER TO "postgres";


ALTER TABLE ONLY "public"."agencies"
    ADD CONSTRAINT "agencies_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."agencies"
    ADD CONSTRAINT "agencies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cooperating_agencies"
    ADD CONSTRAINT "cooperating_aagencies_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cooperating_agencies"
    ADD CONSTRAINT "cooperating_agencies_unique" UNIQUE ("proposal_id", "agency_id");



ALTER TABLE ONLY "public"."criterion"
    ADD CONSTRAINT "criterion_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."departments"
    ADD CONSTRAINT "departments_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."departments"
    ADD CONSTRAINT "departments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."disciplines"
    ADD CONSTRAINT "disciplines_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."disciplines"
    ADD CONSTRAINT "disciplines_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."estimated_budget"
    ADD CONSTRAINT "estimated_budget_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."evaluation_scores"
    ADD CONSTRAINT "evaluation_scores_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."funded_projects"
    ADD CONSTRAINT "funded_projects_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."implementation_site"
    ADD CONSTRAINT "implementation_site_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."priorities"
    ADD CONSTRAINT "priorities_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."priorities"
    ADD CONSTRAINT "priorities_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."project_expenses"
    ADD CONSTRAINT "project expenses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."project_comments"
    ADD CONSTRAINT "project_comments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."project_reports"
    ADD CONSTRAINT "project_reports_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."proposal_assignment_tracker"
    ADD CONSTRAINT "proposal_assignment_tracker_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."proposal_evaluations"
    ADD CONSTRAINT "proposal_evaluations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."proposal_evaluators"
    ADD CONSTRAINT "proposal_evaluators_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."proposal_logs"
    ADD CONSTRAINT "proposal_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."proposal_reject_summary"
    ADD CONSTRAINT "proposal_reject_summary_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."proposal_revision_summary"
    ADD CONSTRAINT "proposal_revision_summary_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."proposal_rnd"
    ADD CONSTRAINT "proposal_rnd_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."proposal_tags"
    ADD CONSTRAINT "proposal_tags_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."proposal_tags"
    ADD CONSTRAINT "proposal_tags_unique" UNIQUE ("proposal_id", "tag_id");



ALTER TABLE ONLY "public"."proposal_version"
    ADD CONSTRAINT "proposal_version_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."proposals"
    ADD CONSTRAINT "proposals_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rubrics"
    ADD CONSTRAINT "rubrics_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sectors"
    ADD CONSTRAINT "sectors_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."sectors"
    ADD CONSTRAINT "sectors_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."evaluators_specialties"
    ADD CONSTRAINT "user_specialties_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."cooperating_agencies"
    ADD CONSTRAINT "cooperating_agencies_agency_fk" FOREIGN KEY ("agency_id") REFERENCES "public"."agencies"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."cooperating_agencies"
    ADD CONSTRAINT "cooperating_agencies_proposal_fk" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."criterion"
    ADD CONSTRAINT "criterion_rubric_id_fkey" FOREIGN KEY ("rubric_id") REFERENCES "public"."rubrics"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."estimated_budget"
    ADD CONSTRAINT "estimated_budget_proposal_id_fkey" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."evaluation_scores"
    ADD CONSTRAINT "evaluation_scores_evaluator_id_fkey" FOREIGN KEY ("evaluator_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."evaluation_scores"
    ADD CONSTRAINT "evaluation_scores_proposal_id_fkey" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."funded_projects"
    ADD CONSTRAINT "funded_projects_project_lead_id_fkey" FOREIGN KEY ("project_lead_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."funded_projects"
    ADD CONSTRAINT "funded_projects_proposal_id_fkey" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."implementation_site"
    ADD CONSTRAINT "implementation_site_proposal_id_fkey" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."notifications"
    ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."project_expenses"
    ADD CONSTRAINT "project expenses_project_reports_id_fkey" FOREIGN KEY ("project_reports_id") REFERENCES "public"."project_reports"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."project_comments"
    ADD CONSTRAINT "project_comments_project_reports_id_fkey" FOREIGN KEY ("project_reports_id") REFERENCES "public"."project_reports"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."project_comments"
    ADD CONSTRAINT "project_comments_users_id_fkey" FOREIGN KEY ("users_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."project_reports"
    ADD CONSTRAINT "project_reports_funded_project_id_fkey" FOREIGN KEY ("funded_project_id") REFERENCES "public"."funded_projects"("id");



ALTER TABLE ONLY "public"."project_reports"
    ADD CONSTRAINT "project_reports_submitted_by_proponent_id_fkey" FOREIGN KEY ("submitted_by_proponent_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_assignment_tracker"
    ADD CONSTRAINT "proposal_assignment_tracker_evaluator_id_fkey" FOREIGN KEY ("evaluator_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_assignment_tracker"
    ADD CONSTRAINT "proposal_assignment_tracker_proposal_id_fkey" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_evaluations"
    ADD CONSTRAINT "proposal_evaluations_proposal_evaluators_id_fkey" FOREIGN KEY ("proposal_evaluators_id") REFERENCES "public"."proposal_evaluators"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_evaluations"
    ADD CONSTRAINT "proposal_evaluations_proposal_id_fkey" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_evaluations"
    ADD CONSTRAINT "proposal_evaluations_rubric_id_fkey" FOREIGN KEY ("rubric_id") REFERENCES "public"."rubrics"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_evaluators"
    ADD CONSTRAINT "proposal_evaluators_evaluator_id_fkey" FOREIGN KEY ("evaluator_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_evaluators"
    ADD CONSTRAINT "proposal_evaluators_forwarded_by_rnd_fkey" FOREIGN KEY ("forwarded_by_rnd") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_evaluators"
    ADD CONSTRAINT "proposal_evaluators_proposal_id_fkey" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_logs"
    ADD CONSTRAINT "proposal_logs_proposal_id_fkey" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_logs"
    ADD CONSTRAINT "proposal_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_reject_summary"
    ADD CONSTRAINT "proposal_reject_summary_proposal_id_fkey" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_reject_summary"
    ADD CONSTRAINT "proposal_reject_summary_rnd_id_fkey" FOREIGN KEY ("rnd_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_revision_summary"
    ADD CONSTRAINT "proposal_revision_summary_proposal_id_fkey" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_revision_summary"
    ADD CONSTRAINT "proposal_revision_summary_rnd_id_fkey" FOREIGN KEY ("rnd_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_rnd"
    ADD CONSTRAINT "proposal_rnd_proposal_id_fkey" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_rnd"
    ADD CONSTRAINT "proposal_rnd_rnd_id_fkey" FOREIGN KEY ("rnd_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_tags"
    ADD CONSTRAINT "proposal_tags_proposal_fk" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposal_tags"
    ADD CONSTRAINT "proposal_tags_tag_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."proposal_version"
    ADD CONSTRAINT "proposal_version_proposal_id_fkey" FOREIGN KEY ("proposal_id") REFERENCES "public"."proposals"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposals"
    ADD CONSTRAINT "proposals_agency_id_fkey" FOREIGN KEY ("agency_id") REFERENCES "public"."agencies"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposals"
    ADD CONSTRAINT "proposals_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposals"
    ADD CONSTRAINT "proposals_discipline_id_fkey" FOREIGN KEY ("discipline_id") REFERENCES "public"."disciplines"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposals"
    ADD CONSTRAINT "proposals_proponent_id_fkey" FOREIGN KEY ("proponent_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."proposals"
    ADD CONSTRAINT "proposals_sector_id_fkey" FOREIGN KEY ("sector_id") REFERENCES "public"."sectors"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."evaluators_specialties"
    ADD CONSTRAINT "user_specialties_department_id_fkey" FOREIGN KEY ("department_id") REFERENCES "public"."departments"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."evaluators_specialties"
    ADD CONSTRAINT "user_specialties_evaluator_id_fkey" FOREIGN KEY ("evaluator_id") REFERENCES "public"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."users"
    ADD CONSTRAINT "users_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Allow authenticated insert agencies" ON "public"."agencies" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Allow public read agencies" ON "public"."agencies" FOR SELECT USING (true);



CREATE POLICY "Public read agencies" ON "public"."agencies" FOR SELECT USING (true);



CREATE POLICY "Public read disciplines" ON "public"."disciplines" FOR SELECT USING (true);



CREATE POLICY "Public read priorities" ON "public"."priorities" FOR SELECT USING (true);



CREATE POLICY "Public read sectors" ON "public"."sectors" FOR SELECT USING (true);



CREATE POLICY "Public read tags" ON "public"."tags" FOR SELECT USING (true);



ALTER TABLE "public"."agencies" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "allow_authenticated_all" ON "public"."agencies" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."cooperating_agencies" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."criterion" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."departments" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."disciplines" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."estimated_budget" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."evaluation_scores" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."evaluators_specialties" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."funded_projects" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."implementation_site" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."notifications" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."project_reports" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."proposal_assignment_tracker" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."proposal_evaluations" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."proposal_evaluators" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."proposal_logs" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."proposal_revision_summary" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."proposal_rnd" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."proposal_tags" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."proposal_version" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."proposals" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."rubrics" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."sectors" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."tags" TO "anon" USING (true) WITH CHECK (true);



CREATE POLICY "allow_authenticated_all" ON "public"."users" TO "postgres", "anon" USING (true) WITH CHECK (true);



CREATE POLICY "aunthenticated_to_all" ON "public"."users" USING (true) WITH CHECK (true);



ALTER TABLE "public"."cooperating_agencies" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."criterion" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."departments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."disciplines" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."estimated_budget" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."evaluation_scores" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."evaluators_specialties" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."funded_projects" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."implementation_site" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."notifications" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."priorities" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."project_comments" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."project_expenses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."project_reports" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."proposal_assignment_tracker" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."proposal_evaluations" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."proposal_evaluators" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."proposal_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."proposal_reject_summary" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."proposal_revision_summary" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."proposal_rnd" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."proposal_tags" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."proposal_version" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."proposals" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."rubrics" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."sectors" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tags" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

























































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."agencies" TO "anon";
GRANT ALL ON TABLE "public"."agencies" TO "authenticated";
GRANT ALL ON TABLE "public"."agencies" TO "service_role";



GRANT ALL ON SEQUENCE "public"."agencies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."agencies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."agencies_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."cooperating_agencies" TO "anon";
GRANT ALL ON TABLE "public"."cooperating_agencies" TO "authenticated";
GRANT ALL ON TABLE "public"."cooperating_agencies" TO "service_role";



GRANT ALL ON SEQUENCE "public"."cooperating_aagencies_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."cooperating_aagencies_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."cooperating_aagencies_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."criterion" TO "anon";
GRANT ALL ON TABLE "public"."criterion" TO "authenticated";
GRANT ALL ON TABLE "public"."criterion" TO "service_role";



GRANT ALL ON SEQUENCE "public"."criterion_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."criterion_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."criterion_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."departments" TO "anon";
GRANT ALL ON TABLE "public"."departments" TO "authenticated";
GRANT ALL ON TABLE "public"."departments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."departments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."departments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."departments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."disciplines" TO "anon";
GRANT ALL ON TABLE "public"."disciplines" TO "authenticated";
GRANT ALL ON TABLE "public"."disciplines" TO "service_role";



GRANT ALL ON SEQUENCE "public"."disciplines_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."disciplines_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."disciplines_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."estimated_budget" TO "anon";
GRANT ALL ON TABLE "public"."estimated_budget" TO "authenticated";
GRANT ALL ON TABLE "public"."estimated_budget" TO "service_role";



GRANT ALL ON SEQUENCE "public"."estimated_budget_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."estimated_budget_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."estimated_budget_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."evaluation_scores" TO "anon";
GRANT ALL ON TABLE "public"."evaluation_scores" TO "authenticated";
GRANT ALL ON TABLE "public"."evaluation_scores" TO "service_role";



GRANT ALL ON SEQUENCE "public"."evaluation_scores_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."evaluation_scores_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."evaluation_scores_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."evaluators_specialties" TO "anon";
GRANT ALL ON TABLE "public"."evaluators_specialties" TO "authenticated";
GRANT ALL ON TABLE "public"."evaluators_specialties" TO "service_role";



GRANT ALL ON TABLE "public"."funded_projects" TO "anon";
GRANT ALL ON TABLE "public"."funded_projects" TO "authenticated";
GRANT ALL ON TABLE "public"."funded_projects" TO "service_role";



GRANT ALL ON SEQUENCE "public"."funded_projects_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."funded_projects_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."funded_projects_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."implementation_site" TO "anon";
GRANT ALL ON TABLE "public"."implementation_site" TO "authenticated";
GRANT ALL ON TABLE "public"."implementation_site" TO "service_role";



GRANT ALL ON SEQUENCE "public"."implementation_site_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."implementation_site_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."implementation_site_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."notifications" TO "anon";
GRANT ALL ON TABLE "public"."notifications" TO "authenticated";
GRANT ALL ON TABLE "public"."notifications" TO "service_role";



GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."notifications_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."priorities" TO "anon";
GRANT ALL ON TABLE "public"."priorities" TO "authenticated";
GRANT ALL ON TABLE "public"."priorities" TO "service_role";



GRANT ALL ON SEQUENCE "public"."priorities_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."priorities_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."priorities_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."project_expenses" TO "anon";
GRANT ALL ON TABLE "public"."project_expenses" TO "authenticated";
GRANT ALL ON TABLE "public"."project_expenses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."project expenses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."project expenses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."project expenses_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."project_comments" TO "anon";
GRANT ALL ON TABLE "public"."project_comments" TO "authenticated";
GRANT ALL ON TABLE "public"."project_comments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."project_comments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."project_comments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."project_comments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."project_reports" TO "anon";
GRANT ALL ON TABLE "public"."project_reports" TO "authenticated";
GRANT ALL ON TABLE "public"."project_reports" TO "service_role";



GRANT ALL ON SEQUENCE "public"."project_reports_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."project_reports_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."project_reports_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."proposal_assignment_tracker" TO "anon";
GRANT ALL ON TABLE "public"."proposal_assignment_tracker" TO "authenticated";
GRANT ALL ON TABLE "public"."proposal_assignment_tracker" TO "service_role";



GRANT ALL ON SEQUENCE "public"."proposal_assignment_tracker_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proposal_assignment_tracker_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proposal_assignment_tracker_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."proposal_evaluations" TO "anon";
GRANT ALL ON TABLE "public"."proposal_evaluations" TO "authenticated";
GRANT ALL ON TABLE "public"."proposal_evaluations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."proposal_evaluations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proposal_evaluations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proposal_evaluations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."proposal_evaluators" TO "anon";
GRANT ALL ON TABLE "public"."proposal_evaluators" TO "authenticated";
GRANT ALL ON TABLE "public"."proposal_evaluators" TO "service_role";



GRANT ALL ON SEQUENCE "public"."proposal_evaluators_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proposal_evaluators_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proposal_evaluators_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."proposal_logs" TO "anon";
GRANT ALL ON TABLE "public"."proposal_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."proposal_logs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."proposal_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proposal_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proposal_logs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."proposal_reject_summary" TO "anon";
GRANT ALL ON TABLE "public"."proposal_reject_summary" TO "authenticated";
GRANT ALL ON TABLE "public"."proposal_reject_summary" TO "service_role";



GRANT ALL ON SEQUENCE "public"."proposal_reject_summary_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proposal_reject_summary_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proposal_reject_summary_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."proposal_revision_summary" TO "anon";
GRANT ALL ON TABLE "public"."proposal_revision_summary" TO "authenticated";
GRANT ALL ON TABLE "public"."proposal_revision_summary" TO "service_role";



GRANT ALL ON SEQUENCE "public"."proposal_revision_summary_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proposal_revision_summary_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proposal_revision_summary_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."proposal_rnd" TO "anon";
GRANT ALL ON TABLE "public"."proposal_rnd" TO "authenticated";
GRANT ALL ON TABLE "public"."proposal_rnd" TO "service_role";



GRANT ALL ON SEQUENCE "public"."proposal_rnd_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proposal_rnd_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proposal_rnd_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."proposal_tags" TO "anon";
GRANT ALL ON TABLE "public"."proposal_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."proposal_tags" TO "service_role";



GRANT ALL ON SEQUENCE "public"."proposal_tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proposal_tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proposal_tags_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."proposal_version" TO "anon";
GRANT ALL ON TABLE "public"."proposal_version" TO "authenticated";
GRANT ALL ON TABLE "public"."proposal_version" TO "service_role";



GRANT ALL ON SEQUENCE "public"."proposal_version_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proposal_version_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proposal_version_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."proposals" TO "anon";
GRANT ALL ON TABLE "public"."proposals" TO "authenticated";
GRANT ALL ON TABLE "public"."proposals" TO "service_role";



GRANT ALL ON SEQUENCE "public"."proposals_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."proposals_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."proposals_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rubrics" TO "anon";
GRANT ALL ON TABLE "public"."rubrics" TO "authenticated";
GRANT ALL ON TABLE "public"."rubrics" TO "service_role";



GRANT ALL ON SEQUENCE "public"."rubrics_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."rubrics_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."rubrics_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sectors" TO "anon";
GRANT ALL ON TABLE "public"."sectors" TO "authenticated";
GRANT ALL ON TABLE "public"."sectors" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sectors_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sectors_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sectors_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."user_specialties_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_specialties_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_specialties_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."users" TO "anon";
GRANT ALL ON TABLE "public"."users" TO "authenticated";
GRANT ALL ON TABLE "public"."users" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";

drop policy "allow_authenticated_all" on "public"."users";


  create policy "allow_authenticated_all"
  on "public"."users"
  as permissive
  for all
  to anon, postgres
using (true)
with check (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


